### ISSUE TITLE
Final touches

### ISSUE THREAD

**Issue by AntonioGGovea** [unosquare/modgen.js#14]
In the store, remember to respect immutability. Check the deleteUserInputArr action.

In prompt templates, you can initialize msjs with the master prompt in the same line.

Try to be consistent if you are using quotes or double quotes throughout the project, I usually prefer simple quotes ('). For this an general formatting, please implement eslint

Rethink which console logs or comments you still need, if you no longer need some of them, please remove them.

Add a title to the page

**Comment by geoperez** [comment]
@AntonioGGovea maybe he needs to implement eslint.

**Comment by AntonioGGovea** [comment]
yes that may help
