### ISSUE TITLE
Create new Model Generator

### ISSUE THREAD

**Issue by AntonioGGovea** [unosquare/modgen.js#7]
We need to have a platform that will allow the user to input a series of model-result examples in order to train the LLM.
This series of examples will later be use to generate new results through a prompt.

- Add two text areas; one to provide a model and other for the result.
- After providing one or more examples, the user should be able to enter a model and ask for a result by clicking a button.
- Experiment with various prompts to find the best possible.
- Make sure you include validation to the inputs.

**Comment by ghost** [comment]
IN PROGRESS

**Comment by geoperez** [comment]
@AllierByron usa el estatus del ticket en lugar de un comentario:

![image](https://github.com/unosquare/modgen.js/assets/1775792/14785f32-c32f-4e3a-899d-06c0597bb33f)
